# Generated by Django 5.1.1 on 2024-10-18 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stu_record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('phoneNo', models.BigIntegerField()),
                ('city', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=20)),
            ],
        ),
    ]
