# Generated by Django 5.1.1 on 2024-10-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('all_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stu_record',
            name='rollNo',
            field=models.IntegerField(default=0),
        ),
    ]
